8053 refactor incorrect local test
medic/medic-webapp pull request #8058
Opened 2023-02-03 05:02 UTC by ngaruko

# Description

Migrating  test from protractor to wdio.

medic/cht-core #7723 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8053-refactor-incorrect-local-test/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8053-refactor-incorrect-local-test/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8053-refactor-incorrect-local-test/docker-compose/cht-couchdb-clustered.yml)
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-03-09 01:35 UTC, garethbowen commented
@tatilepizs Just checking that you saw this?

2023-03-09 21:31 UTC, tatilepizs requested changes
This looks great @ngaruko !
Thank you for doing this. I just left a couple of question/suggestion.

2023-03-14 15:37 UTC, tatilepizs approved these changes
Looks good!
Thank you @ngaruko  for the changes 🎉 
I just leave a small suggestion

2023-03-14 15:37 UTC, tatilepizs commented on tests/e2e/default/enketo/pregnancy.wdio-spec.js
> +    expect(tasks.length).to.equal(3);//TODO: investigate why 'Pregnancy home visit' task is not being generated
I think that this comment can also be removed right? 🙂

2023-03-18 23:45 UTC, merged